### ISSUE TITLE
Bug: Layout issue in footer & on  '/clubs' in cta-button in <370px size.

### ISSUE THREAD

**Issue by TahaHameed23** [MilanCommunity/Milan#1086]
### Description

Footer & cta-button (on:  /clubs) layout issues in screen size less than 370px.

### Screenshots

- Footer layout issue in <370px screen size.

![IMG_20230926_233511](https://github.com/MilanCommunity/Milan/assets/89855847/7d2218bb-f1dc-43d5-ad2a-d846e5e203bf)

- cta-btn (donate) layout issue in "/clubs" route. 

![Screenshot_2023-09-26-23-34-50-02_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/MilanCommunity/Milan/assets/89855847/1e7bf68a-8ebc-49e5-9bc1-00030674d69d)

### Browser 🥦

Google Chrome

### Checklist ✅

- [x] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

**Comment by tamalCodes** [comment]
I want to put this issue on hold as some changes related to the entire website's responsiveness are being done in #1083 , so in case something is missed we can catch up on this issue. Thanks for spending the time to raise this issue.

**Comment by TahaHameed23** [comment]
hey @tamalCodes,I had the changes commited in my fork since I made this issue, it could have been solved as it was small issue.

**Comment by tamalCodes** [comment]
Hi @TahaHameed23 , you can make a PR for this. I closed 3-4 issues by mistake while I was trying something. My bad.
Thanks for bringing this to my notice.

Do make a PR, assigning it to you 🚀 
<br/>

## 📑 Checklist in case you missed something

- [Local project setup, .env](https://github.com/MilanCommunity/Milan#1%EF%B8%8F-setting-up-the-project-locally) for the frontend.
- [Contributing guidelines](https://github.com/MilanCommunity/Milan#2%EF%B8%8F-contributing-guidelines--more) to be followed.


Please maintain structure, use conventional pull request titles, and avoid spam to avoid closure or bans.

**Comment by TahaHameed23** [comment]
No problem, & thanks for reconsidering!
